on: push
name: Slack
jobs:
  slack:
    name: Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
